---
apiVersion: v1
kind: Service
metadata:
  name: employee-api
spec:
  selector:
    app: employee-api
    tier: api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: employee-cli
spec:
  selector:
    app: employeecli
    tier: employee-cli
  ports:
  - protocol: "TCP"
    port: 8089
    targetPort: 8089
  type: LoadBalancer


---
apiVersion: v1
kind: Service
metadata:
  name: employee-sql
spec:
  selector:
    app: employee-sql
    tier: sql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
