---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apisql
spec:
  selector:
    matchLabels:
      app: employee-sql
      tier: sql
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: employee-sql
        tier: sql
        track: stable
    spec:
      containers:
        - name: employee-sql
          image: "narjess6/employees-sql:1.0"
          ports:
            - name: sql
              containerPort: 5432
